import Head from "next/head";
import $ from "jquery";
import Script from 'next/script';
import Link from "next/link";
import { FiArrowDown } from "react-icons/fi";
import avian from "../public/avian.png";
import wavn from "../public/wavn.png";
import Image from "next/image";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></Script>
        <Script>
          window.onload = function() {
            document.getElementById("avn").value = document.getElementById("avn").value;
          document.getElementById("wavn").value = document.getElementsByName("wavn")[0].value;
          var src = document.getElementById("avn"),
          dst = document.getElementById("wavn");
          src.addEventListener("input", function() {
            dst.value = src.value;
                                 });
                                 
        };
        </Script>
      </Head>

      <div className="navbar bg-base-100">
  <div className="navbar-start">
    <div className="dropdown">
      <label tabIndex={0} className="btn btn-ghost lg:hidden">
        <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h8m-8 6h16" /></svg>
      </label>
      <ul tabIndex={0} className="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
        <li><a>Item 1</a></li>
        <li tabIndex={0}>
          <a className="justify-between">
            Parent
            <svg className="fill-current" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M8.59,16.58L13.17,12L8.59,7.41L10,6L16,12L10,18L8.59,16.58Z"/></svg>
          </a>
          <ul className="p-2">
            <li><a>Submenu 1</a></li>
            <li><a>Submenu 2</a></li>
          </ul>
        </li>
        <li><a>Item 3</a></li>
      </ul>
    </div>
    <a className="btn btn-ghost normal-case text-xl">Wrapped Avian</a>
  </div>
  <div className="navbar-center hidden lg:flex">
    <ul className="menu menu-horizontal p-0">
      <li><a>Item 1</a></li>
      <li tabIndex={0}>
        <a>
          Parent
          <svg className="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"/></svg>
        </a>
        <ul className="p-2">
          <li><a>Submenu 1</a></li>
          <li><a>Submenu 2</a></li>
        </ul>
      </li>
      <li><a>Item 3</a></li>
    </ul>
  </div>
  <div className="navbar-end">
    <a className="btn">Dev Docs</a>
  </div>
</div>

<div className="card w-96 bg-base-100 shadow-xl m-auto mt-24">
  <div className="card-body">
    <h1 className="text-center text-3xl">Wrap your Avian!</h1>

    <div className="form-control">
<form></form>

  <label className="label">
    <span className="label-text">Avian</span>
  </label>
  <label className="input-group">
    <span><Image
      src={avian}
      alt="Picture of Avian"
      width={500}
      height={500}
    /></span>
    <div className="indicator">
  <span className="indicator-item badge">Required</span>
    <input type="text" placeholder="7" id="avn" className="input input-bordered" required/>
    </div>
  </label>

    <div class="divider"><FiArrowDown className="text-8xl" /></div>

<label className="label">
    <span className="label-text">WAVN</span>
  </label>
  <label className="input-group">
    <span><Image
      src={wavn}
      alt="Picture of WAVN"
      width={500}
      height={500}
    /></span>
    
    <input type="text" placeholder="" id="wavn" className="input input-bordered" onInput={(e) => setInput(e.avn.value)} disabled />
    
  </label>
  
  <span className="mt-4 text-center">Wallet Address</span>
  <input type="text" placeholder="Type here" className="input input-bordered input-info w-full max-w-xs" required/>
 
    
    </div>

  </div>
</div>

</div>
  );
}